apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: blue-green-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: harbor-test.ibas.gov.bd/ringko/zero-downtime-app:v2
        ports:
        - containerPort: 3000
