apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rolling
  namespace: blue-green-canary
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: app
        image: harbor-test.ibas.gov.bd/ringko/zero-downtime-app:v1
        ports:
        - containerPort: 3000
