apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: blue-green-canary
spec:
  selector:
    app: myapp
    version: green  # change to green to switch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
